### ISSUE TITLE
Hey etsinko - trying to contact you, I have a request to ask

### ISSUE THREAD

**Issue by 121940kz** [etsinko/pymonoprice#2]
This is not an issue, but I don't know of any other way to contact you. I have a request to make the home assistant monoprice 6 zone 6 source amp integration better. Right now it only works with a direct RS232 connection and you specify the port in the .yaml (port: /dev/ttyUSB0) i would like to propose also adding support for the itach by specifying the port as (port: iTach) and this would direct the requests to the itach ip address which would need to be another field added. I am the developer who wrote the android app for the monoprice 6 zone 6 source amps, and I also have a python integration which i wrote for people who didn't want to spend that much on the iTach device. https://github.com/121940kz/Monoprice-Whole-Home-Audio-Android-App-Raspberry-Pi-Server

Can you email me back and kadin@kztechconsulting.com

**Comment by soccerob** [comment]
Has there been any progress on this request? I would like to be able to control with the iTach device as well.

**Comment by etsinko** [comment]
AFAIK this should work out of the box: https://pythonhosted.org/pyserial/url_handlers.html 

I can't test because I don't have iTach. Feel free to fork and do a pull request if any changes to code are required.

**Comment by etsinko** [comment]
Let me know if it works
